openapi: 3.0.0

info:
  title: API Server
  version: 1.0.0
  description: API per controllo dispositivi IoT

servers:
  - url: http://bolide.local:8080 

tags:
  - name: Weather
  - name: Crypto
  - name: ESP

paths:
  /get_weather:
    $ref: './paths/weather.yaml#/get_weather'

  /get_crypto_data:
    $ref: './paths/crypto.yaml#/get_crypto_data'

  /esp:
    $ref: './paths/esp.yaml#/esp_list'

  /esp/device/{id}:
    $ref: './paths/esp.yaml#/esp_get_by_id'

  /esp/{type}:
    $ref: './paths/esp.yaml#/esp_list_by_type'

  /esp/{id}/command:
    $ref: './paths/esp.yaml#/esp_command'

components:
  schemas:
    Weather:
      $ref: './schemas/weather.yaml#/Weather'
    Crypto:
      $ref: './schemas/crypto.yaml#/Crypto'
    EspDevice:
      $ref: './schemas/esp.yaml#/EspDevice'
    EspListPayload:
      $ref: './schemas/esp.yaml#/EspListPayload'
    EspListResponse:
      $ref: './schemas/esp.yaml#/EspListResponse'
    EspCommandRequest:
      $ref: './schemas/esp.yaml#/EspCommandRequest'
    EspCommandResponsePayload:
      $ref: './schemas/esp.yaml#/EspCommandResponsePayload'
    EspGetResponsePayload:
      $ref: './schemas/esp.yaml#/EspGetResponsePayload'
    EspGetResponse:
      $ref: './schemas/esp.yaml#/EspGetResponse'
    EspCommandResponse:
      $ref: './schemas/esp.yaml#/EspCommandResponse'